# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

my_abs <- function(x) {
    .Call('_evi_my_abs', PACKAGE = 'evi', x)
}

ell_nb_i_fun <- function(beta_nb, alpha_nb, x_nb_ext_i, y_i) {
    .Call('_evi_ell_nb_i_fun', PACKAGE = 'evi', beta_nb, alpha_nb, x_nb_ext_i, y_i)
}

delldtheta_nb_i_fun <- function(beta_nb, alpha_nb, x_nb_ext_i, y_i) {
    .Call('_evi_delldtheta_nb_i_fun', PACKAGE = 'evi', beta_nb, alpha_nb, x_nb_ext_i, y_i)
}

d2elldtheta2_nb_i_fun <- function(beta_nb, alpha_nb, x_nb_ext_i, y_i) {
    .Call('_evi_d2elldtheta2_nb_i_fun', PACKAGE = 'evi', beta_nb, alpha_nb, x_nb_ext_i, y_i)
}

ell_pl_i_fun <- function(beta_pl, c_pl, x_pl_ext_i, y_i) {
    .Call('_evi_ell_pl_i_fun', PACKAGE = 'evi', beta_pl, c_pl, x_pl_ext_i, y_i)
}

delldbeta_pl_i_fun_approx <- function(beta_pl, c_pl, x_pl_ext_i, y_i) {
    .Call('_evi_delldbeta_pl_i_fun_approx', PACKAGE = 'evi', beta_pl, c_pl, x_pl_ext_i, y_i)
}

d2elldbeta2_pl_i_fun_approx <- function(beta_pl, c_pl, x_pl_ext_i, y_i) {
    .Call('_evi_d2elldbeta2_pl_i_fun_approx', PACKAGE = 'evi', beta_pl, c_pl, x_pl_ext_i, y_i)
}

log_lik_fun <- function(gamma_z, gamma_pl, beta_nb, alpha_nb, beta_pl, c_pl, x_mult_z_ext, x_mult_pl_ext, x_nb_ext, x_pl_ext, y) {
    .Call('_evi_log_lik_fun', PACKAGE = 'evi', gamma_z, gamma_pl, beta_nb, alpha_nb, beta_pl, c_pl, x_mult_z_ext, x_mult_pl_ext, x_nb_ext, x_pl_ext, y)
}

update_bfgs_fun <- function(gamma_z_in, gamma_pl_in, beta_nb_in, alpha_nb_in, beta_pl_in, c_pl, x_mult_z_ext, x_mult_pl_ext, x_nb_ext, x_pl_ext, y, max_upd_par, no_m_bfgs_steps) {
    .Call('_evi_update_bfgs_fun', PACKAGE = 'evi', gamma_z_in, gamma_pl_in, beta_nb_in, alpha_nb_in, beta_pl_in, c_pl, x_mult_z_ext, x_mult_pl_ext, x_nb_ext, x_pl_ext, y, max_upd_par, no_m_bfgs_steps)
}

